#' Toy undirected network generated by ER-model
#'
#' A list of an igraph object and a data frame
#'
#' @docType data
#'
#' @usage data(toy_er)
#'
#' @format A list object of an igraph obejct and a data frame
#'
#' @return A list object
#'
"toy_er"
